Update starting agent

diff --git a/stool-agent b/stool-agent
--- a/stool-agent
+++ b/stool-agent
@@ -11,43 +11,61 @@ import sys
 import argparse
 
 parser = argparse.ArgumentParser(description = 'Running and stopping an ssh-agent on a host')
-parser.add_argument('-s', action = 'store_true', help = 'start an agent on a the current host')
-parser.add_argument('-k', action = 'store_true', help = 'Kill the current agent on a host')
+parser.add_argument('-s', action = 'store_true', help = 'start an agent on the current host')
+parser.add_argument('-k', action = 'store_true', help = 'Kill the current agent on the host')
+parser.add_argument('-l', action = 'store_true', help = 'List the current agent on the host')
 args = parser.parse_args()
 
 if len(sys.argv) == 1:
     parser.print_help(sys.stderr)
     sys.exit(1)
 
-host_name = os.popen('hostname').read().strip()
-user_name = os.getenv('USER')
-
 if args.s:
-    if bool(os.popen('if [ -f ~/.ssh/id_rsa ]; then echo True; fi').read().strip()):
-        if not bool(os.popen('if ps -elf | grep ssh-agent | grep -v grep | grep -q $USER; then echo True; fi').read()):
-            os.system(f"""
-echo "Starting an agent on {host_name} ..."
-install -d /home/{user_name}/.ssh_auth
-eval `ssh-agent -s`
-ssh-add
-echo $SSH_AUTH_SOCK > /home/{user_name}/.ssh_auth/{host_name}
-            """)
-        else:
-            os.system(f"""
-if [ -z $SSH_AUTH_SOCK ]; then
-export SSH_AUTH_SOCK=`cat /home/{user_name}/.ssh_auth/{host_name}`
+    os.system("""
+    if [ -f ~/.ssh/id_rsa ]; then
+    if ! ps -elf | grep ssh-agent | grep -v grep | grep -q $USER; then
+    echo "Starting an agent on $(hostname) ..."
+    install -d /home/$USER/.ssh_auth
+    eval `ssh-agent -s`
+    ssh-add
+    echo $SSH_AUTH_SOCK > /home/$USER/.ssh_auth/$(hostname)
+    if ! grep -q SSH_AUTH_SOCK /home/$USER/.bashrc; then
+    echo "
+# >>> ssh-agent >>>
+if [ -f /home/$USER/.ssh_auth/\$(hostname) ]; then
+export SSH_AUTH_SOCK=\`cat /home/$USER/.ssh_auth/\$(hostname)\`
 fi
-echo "The ssh-agent is running on {host_name}."
-            """)
-    else:
-        print('SSH keys not found. Add your id_rsa keys to "~/.ssh".')
+# <<< ssh-agent <<<
+" >> /home/$USER/.bashrc
+    fi
+    echo "The ssh-agent authentication is added to ~/.bashrc. Run 'source ~/.bashrc' to apply the changes."
+    else
+    if [ -z $SSH_AUTH_SOCK ]; then
+    echo "An agent is running but the authentication is not available. Stop the agent with -k and rerun the command."
+    fi
+    echo "The ssh-agent is running on $(hostname)."
+    fi
+    else
+    echo "SSH keys not found. Add your id_rsa keys to '~/.ssh'."
+    fi
+    """)
 
 if args.k:
-    if bool(os.popen('if ps -elf | grep ssh-agent | grep -v grep | grep -q $USER; then echo True; fi').read()):
-        os.system(f"""
-echo "Stopping the current agent on {host_name} ..."
-kill `ps -elf | grep ssh-agent | grep -v grep | grep $USER | awk '{{print $4}}'`
-rm -f /home/{user_name}/.ssh_auth/{host_name}
-            """)
-    else:
-        print(f"Not a running agent found on {host_name}.")
+    os.system("""
+    if ps -elf | grep ssh-agent | grep -v grep | grep -q $USER; then
+    echo "Stopping the current agent on $(hostname) ..."
+    kill `ps -elf | grep ssh-agent | grep -v grep | grep $USER | awk '{print $4}'`
+    rm -f /home/$USER/.ssh_auth/$(hostname)
+    else
+    echo "No running agent found on $(hostname)."
+    fi
+    """)
+
+if args.l:
+    os.system("""
+    if ps -elf | grep ssh-agent | grep -v grep | grep -q $USER; then
+    ps -elf | grep ssh-agent | grep -v grep | grep $USER
+    else
+    echo "No running agent found on $(hostname)."
+    fi
+    """)
