Merge agent to the main toolkit

diff --git a/stool b/stool
--- a/stool
+++ b/stool
@@ -27,6 +27,7 @@ parser.add_argument('--ncpu', action = 'store_true', help = 'show number of avai
 parser.add_argument('--ngpu', action = 'store_true', help = 'show number of available gpus')
 parser.add_argument('--gpu', action = 'store_true', help = 'show gpu resources')
 parser.add_argument('--license', action = 'store_true', help = 'show available licenses')
+parser.add_argument('--agent', choices = ['start','stop','list'], help = 'start/stop/list ssh-agents on the current host', metavar = '')
 args = parser.parse_args()
 
 if len(sys.argv) == 1:
@@ -189,3 +190,54 @@ if args.quota:
             echo \n
             fi           
             """)
+
+if args.agent:
+    if args.agent == 'start':
+        os.system("""
+        if [ -f ~/.ssh/id_rsa ]; then
+        if ! ps -elf | grep ssh-agent | grep -v grep | grep -q $USER; then
+        echo "Starting an agent on $(hostname) ..."
+        install -d /home/$USER/.ssh_auth
+        eval `ssh-agent -s`
+        ssh-add
+        echo $SSH_AUTH_SOCK > /home/$USER/.ssh_auth/$(hostname)
+        if ! grep -q SSH_AUTH_SOCK /home/$USER/.bashrc; then
+        echo "
+# >>> ssh-agent >>>
+if [ -f /home/$USER/.ssh_auth/\$(hostname) ]; then
+export SSH_AUTH_SOCK=\`cat /home/$USER/.ssh_auth/\$(hostname)\`
+fi
+# <<< ssh-agent <<<
+" >> /home/$USER/.bashrc
+        fi
+        echo "The ssh-agent authentication is added to ~/.bashrc. Run 'source ~/.bashrc' to apply the changes."
+        else
+        if [ -z $SSH_AUTH_SOCK ]; then
+        echo "An agent is running but the authentication is not available. Stop the agent with -k and rerun the command."
+        fi
+        echo "The ssh-agent is running on $(hostname)."
+        fi
+        else
+        echo "SSH keys not found. Add your id_rsa keys to '~/.ssh'."
+        fi
+        """)
+
+    if args.agent == 'stop':
+        os.system("""
+        if ps -elf | grep ssh-agent | grep -v grep | grep -q $USER; then
+        echo "Stopping the current agent on $(hostname) ..."
+        kill `ps -elf | grep ssh-agent | grep -v grep | grep $USER | awk '{print $4}'`
+        rm -f /home/$USER/.ssh_auth/$(hostname)
+        else
+        echo "No running agent found on $(hostname)."
+        fi
+        """)
+
+    if args.agent == 'list':
+        os.system("""
+        if ps -elf | grep ssh-agent | grep -v grep | grep -q $USER; then
+        ps -elf | grep ssh-agent | grep -v grep | grep $USER
+        else
+        echo "No running agent found on $(hostname)."
+        fi
+        """)
